= 2023 취직 후기
An Nyeong <me@annyeong.me>
:description:
:keywords:
:created_at: 2023-12-17 14:23:55

23년 10월에 인생 처음으로 소프트웨어 엔지니어로서 일을 하게 되었다.
구직을 하는 과정에서 겪었던 어려움과 생각의 변화를 추후에 참고하기 위하여 정리한다.

== 배경

소프트웨어 엔지니어, 혹은 프로그래머를 직업으로 삼고 싶다는 생각은 꽤 오래전부터 했다.
초등학교 때부터 컴퓨터를 좋아하여 프로그래밍 언어를 익히고, 여러 자격증을 땄다.
(개중에는 컴퓨터그래픽스운용기능사와 웹디자인기능사 같이 단순히 컴퓨터를 쓴다는 이유만으로 딴,
프로그래밍과는 큰 관련 없는 자격증도 있다.)
자연스레 대학도 컴퓨터 공학과로 진학하였고, 나름 수업도 열심히 들었다.

그러나 오랫동안 컴퓨터 과학에 대한 내 태도는 취미 수준을 벗어나지 못하였다.
컴퓨터를 좋아하고 오랫동안 공부하였으나, 내세우고 자랑할만한 성과나 기술에 대한 깊은 이해는 부족하였다.
찍먹과 간보기만을 반복하여 넓게 알고 얕게 아는, 이른바 프로 찍머기스트가 되어버렸다.

되돌아 생각해보면, 이 시점까지의 내게 있어 프로그래밍란 지적 허영심을 채우는 수단, 좋게 얘기해도 지적 유희였다.
체스를 좋아하는 사람이 대회에 나가지 않더라도 새로운 오프닝을 연구하는 것처럼, 어디 쓸 것도 아니면서
새로운 언어나 도구를 탐구하였다.
배우는 것 자체가 목적이고 그 외의 목적이 결여되어있으므로 배운 순간 (혹은 배웠다는 만족을 얻는 순간)
그 목적을 다하였고 결과적으로 아무것도 남지 않았다.
내 머릿속에 만족감과 지식이 남긴 하였으나 그걸 증명하는 것은 또 결이 다른 일이었다.

먼 훗날의 일이고,
당시 나는 학군사관후보생이었다.
취업에 대해 진지하게 생각하지 못하였고,

하나에 올곧게 집중하지 못하였다.

학군단 활동

== 준비

전역하니, 현역 시절 곁눈질로 소식만 전해 듣던 때와는 취업 시장이 많이 바뀌어있었다.
뉴스에는 연이어 "파티가 끝났다"는 기사만이 도배되었다. 코로나가 불러온 유동성과 저금리의 합주가 끝났고,
윤 대통령도 공공기관 파티가 끝났다고 선언하였다. 중소규모 기업의 희망퇴직 소식이 들려왔다.

== 생각이 변한 점

== 이직 준비



[bibliography]
== 참고

. 작성자, 이름.
