= Asciidoc 블로깅 파이프라인 하나씩 구축하기
An Nyeong <me@annyeong.me>
:keywords: hanassig

asciidoc + vim으로 편리하게 블로깅 할 수 있는 파이프라인을 정립하자.

== 목표

- [ ] neovim으로 편리하게 asciidoc 문서를 편집하자
- [ ] 오류를 교정할 수 있는 도구 도입하자
- [ ] 작성 후 웹으로 한 번에 배포할 수 있는 파이프라인을 구축하자

== asciidoc

asciidoc은 기술 문서 작성을 위한 경량 마크업 언어이다. 각주, 참조 등 강력한 기능이 많고, 소스코드로 보더라도 읽기 편리하다.
HTML 뿐 아니라 DocBook, PDF, EPUB 등 다양한 포맷으로 내보낼 수 있다. <<arex>>

EPUB로 내보낼 수 있기에 책 작성에 쓸 수 있을 정도로 구조화된 글을 쓰기에 적당한 포맷일거라는 기대감이 들었다.
다만 기술의 관심도가 낮아 다양한 도구가 없어서 아쉽다. LSP, tree-sitter도 없고, 다양한 문서 편집 프로그램에서 지원하지 않는다는 큰 단점이 있다.

=== 다른 선택지

경량 마크업 언어로는 아무래도 마크다운이 가장 유명하다. 간단하고 쉽게 익힐 수 있으며 관심도가 높다.
여러 프로그램에서 퍼스트 파티로 지원한다. GitHub는 물론이고 슬랙이나 디스코드에서도 마크다운의 일부 문법을 지원하고
노션이나 옵시디언, https://bear.app/[Bear] 같은 노트 앱들은 이제는 마크다운을 지원하지 않는 것을 찾기가 어렵다.

다만 확장성이 부족하다는 것이 나한테는 큰 단점이었다. 마크다운은 단순하고 기능이 적은데, 이를 많은 프로그램에서 서로
다른 방법으로 문법을 확장하여 호환되지 않는다.

이게 상당히 단순한 부분부터 헷갈리고 까다롭다. ``[title](link)``로 링크를 만들면 어디로 걸려야 하는가? 특정 요소에
HTML class 이름을 지정하고 싶다면 어떻게 해야하는가? 특정 위치에 대한 링크를 만들고 싶다면 어떻게 해야하는가?
조금 복잡한 요소를 도입하거나, 글이 길어져 분리하고 싶다면 어떻게 해야하는가? 각주와 미주는 어떻게 처리되는가?
글에 대한 메타데이터는 어떻게 관리해야하는가?

기능을 추가하기 위해 문법을 확장해보면 편리하고 단순한 장점이 퇴색된다. 특히 내부에 HTML이나 mdx을 쓰기 시작하면 더욱 그렇다.
뭔가 확장하고 싶다면 결국 나만의 문법을 정의하고 구현해야하는데, 그게 또 파편화로 이어지는 것이 싫었다.

asciidoc은 마크다운에 없지만 유용하게 쓰이는 문법들이 퍼스트파티로 정의되어있고, 필요한 경우 매크로 문법을 이용하여 확장할 수 있는 점이 좋았다.

가장 간단한 예로, 마크다운 표준 문법으로 제목(h1)은 아래와 같이 정의한다:

[source, markdown]
----
# 글의 제목

이 글에 이어질 본문

## 개요 1
----

글에 이런 저런 추가 정보를 달기 위해서는 마크다운 표준 문법만으로는 부족하다. 보통은 `---`으로 감싼 YAML로 글의 메타 데이터를 작성한다.
이렇게되면 글의 제목, `h1` 태그는 메타데이터로 표기하고, `h2` 수준의 제목부터는 마크다운 문법(`##`)으로 표기하게 된다.

[source, markdown]
----
---
title: 글의 제목
tags: a, b, c
created_at: 2023-01-01 00:00:00
updated_at: 2023-01-01 00:00:00
---

이 글에 이어질 본문

## 개요 1?
----

사실 별 중요한 단점도 아니지만 나는 하나의 문서가 해당 언어로 완결되었으면 좋겠다는 바람이 있어서 asciidoc을 우선하였다.

== neovim + asciidoc

본래는 주 에디터로 https://helix-editor.com/[helix editor]를 사용하였다.
모달 에디터이기에 키보드만으로 모든 동작을 편리하게 쓸 수 있고, 기본적으로 설정된 tree-sitter, LSP 지원이 좋아서 별도의 플러그인에 의지하지 않아도 되어 좋았다.
하지만 조금이라도 정해진 용례에서 벗어나는 경우, 커스텀하기 어려워 사용이 불편하였다. 그리고 asciidoc은, 아쉽게도 정해진 용례가 아니었다.
asciidoc에 대한 tree-sitter, LSP 구현체가 있다면 helix에서도 편하게 쓸 수 있고, 최종적으로는 그게 제일 좋겠지만 굉장한 야크 털깎기라 당장의 불편함을 해결할 수는 없다.

neovim은 helix와 비슷한 모달 에디터이다. 애초에 helix보다 먼저 나왔다.
neovim은 lua 스크립트 언어를 이용하여 에디터를 편리하게 확장할 수 있다. 특정 경우에 대하여 훅을 실행하도록 하면 LSP를 밑바닥부터 짜는 것보다 빠른 속도로 비슷한 효과를 볼 수 있을 것으로 기대했다.

한 달 정도 neovim을 써보니 아래의 불편함을 해소하면 neovim으로 asciidoc을 굉장히 편리하게 편집할 수 있겠다 싶다:

- [ ] 새로운 글 추가가 불편하다
- [ ] 링크를 보기가 불편하다
- [x] 작성한 글 검색이 불편하다
- [ ] 작성하는 글의 개요를 보고싶다
- [ ] HTML 렌더링 결과를 보고 싶다
- [ ] 이미지 추가가 불편하다
- [ ] 내부 링크를 자유롭게 이동하고 싶다
- [ ] 웹 링크를 자유롭게 추가하고 싶다

불편한 점을 하나씩 고쳐보자

=== 설정 디렉토리 구조

나는 vimscript 대신 lua만 쓸 것이다. ``~/.config/nvim``에 설정 파일을 구성한다.
neovim이 실행되면 기본적으로 ``init.lua``를 불러온다. `lua` 디렉토리에 루아 스크립트를 넣어두면
`require 'core.autocmd'` 이런식으로 불러올 수 있다.

. 공통 키맵은 ``keymap.lua``에서 정의한다.

[source]
----
~/.config/nvim
├── init.lua
├── lazy-lock.json
├── ftplugin/ -- 파일 타입별 설정
│   └── asciidoc.lua
├── lua/
│   ├── core/
│   │   ├── autocmd.lua
│   │   ├── config.lua
│   │   ├── keymap.lua -- 공통 키맵
│   │   └── plugins.lua
│   └── plugin/ -- 각 플러그인별 설정
│       └── lspconfig.lua
└── README.md
----

=== 새로운 글 추가가 불편하다

별 다른 설정 없이 ``:e file-name.adoc``로 새 파일 만들고 ``:w``로 저장하고 있다. 크게 두 가지 아쉬운 점이 있다.

. Asciidoc은 글을 작성할 때 왠만하면 작성해야하는 보일러플레이트가 꽤 있다. 템플릿이 있으면 좋겠다.
. 링크로 글을 삽입할 때에는 추가 동작이 필요하다.
.. 먼저 링크를 만든다. `<<file-name.adoc#>>`
.. 해당하는 문서를 만든다. `:e file-name.adoc`
.. 같은 파일 이름을 두 번 적어야 한다. 이 과정에서 실수할 수도 있다.

템플릿부터 만들어보자. vim은 autocmd라는 이름으로 훅을 지원한다. 특정 이벤트가 발생했을 때의 동작을 지정할 수 있다.
`BufNewFile` 훅으로 새 파일이 만들어면 특정 내용을 입력하도록 만들자.

``ftplugin/asciidoc.lua``에 ``autocmd``를 추가한다. ``ftplugin`` 디렉토리 내의 파일은 현재 filetype과 동일할 때에만 실행된다.
`nvim_buf_set_lines` 함수는 버퍼, 즉 열린 파일에 내용을 입력할 수 있도록 해준다.

.ftplugin/asciidoc.lua
[source, lua]
----
local function new_template()
    local content = {}
    table.insert(content, '= Title')
    table.insert(content, ':created_at: ' .. os.date("%Y-%m-%d %H:%M:%S"))

    vim.api.nvim_buf_set_lines(0, 0, -1, false, content)
end

vim.api.nvim_create_autocmd('BufNewFile', {
    callback = new_template
})
----

이렇게 하면 새 파일을 추가하였을 때 자동으로 아래처럼 내용이 채워진다:

[source]
----
 = Title
An Nyeong <me@annyeong.me>
:created_at: 2023-12-10 00:00:00
----

=== 링크 보기가 불편하다

asciidoc에서 다른 파일로 링크를 걸 수 있다. 문법이 크게 두가지 있다:

[source, asciidoc]
----
. xref:other-file.adoc#section[보일 내용]
. <<other-file.adoc#section,보일 내용>>
----

. 특정 섹션을 가리키지 않더라도 `#` 까지는 표기해야한다. 귀찮고 난잡하다.
. 보일 내용은 수동으로 입력해주어야한다. 귀찮다.
. 파일명이 먼저 나온다. 파일명을 왠만하면 영어로 적고 있는데, 영어를 잘 못해서 무슨 링크인지 한눈에 들어오지 않는다.

=== 글을 편리하게 검색하고 싶다

github:[renerocksai/telekasten.nvim]으로 해결하였다.

* `<space>f`: 파일 이름으로 검색한다.
* `<space>g`: 파일 내용으로 검색한다.

vim을 켜지 않은 상태에도, 단순 텍스트 파일이므로 편리하게 검색할 수 있다.

=== 글의 ToC가 보고 싶다

글의 헤더만 모아 볼 수 있다면 전체적인 흐름을 파악하기 쉽다. tree-sitter나 LSP가 있다면 크게 고민할 일이 아닌데,
둘 다 없으므로 다른 방법이 필요하다.

tree-sitter나 LSP가 있기 전에는 ctags를 썼다고 하더라. 몇몇 기능들은 자동으로 vim과 통합되어있기도 하다.
asciidoc ctags로 검색하면 https://github.com/universal-ctags/ctags[universal-ctags]라는 ctags 구현체가 제일 먼저 나온다.
아래와 같이 `-R` 옵션을 주면 재귀적으로 잘 실행하여 `tags` 파일을 만들어준다.

[source]
----
$ /opt/homebrew/bin/ctgas -R ~/Repos/hanassig
----

이걸 neovim과 연동하기 위해 두 가지 작업이 필요하다.

. ctags를 알아서 돌릴 방법
. ctags로 생성한 tags를 잘 읽어서 보여줄 방법

파일이 수정되면 ctags를 자동으로 실행시켜주어야 한다. autocmd에 등록하는 것도 좋지만, 자동으로 해주는 플러그인을
이용하면 더 효율적이고 편리하다.

ctags를 보여주는 플러그인으로는 https://github.com/preservim/tagbar[tagbar]가 유명하다.

[bibliography]
== 참고

. John Grib, https://johngrib.github.io/wiki/my-wiki/[Vimwiki + Jekyll + Github.io로 나만의 위키를 만들자].
. 이재열, https://kodingwarrior.github.io/wiki/appendix/excelcon-2nd/[제 2회 EXCELCON - Neovim으로 생산성 퀀텀점프하기].
. Gilles Castel, https://castel.dev/post/lecture-notes-1/[How I'm able to take notes in mathematics lectures using LaTeX and Vim].
. ihoneymon, https://gist.github.com/ihoneymon/40fd306b4f460f44f4050d3bf73a6637[Asciidoc 으로 전자책 쓰기 - SpringCamp 2016 LETS].
. ihoneymon, https://github.com/ihoneymon/asciidoc-book-template[Asciidoc 으로 시작하는 책쓰기용 템플릿].
. [[[arex]]] Miguel Cobá, https://medium.com/@miguel.coba/asciidoc-to-html-pdf-and-epub-rendering-examples-81bcc64dcaa0[AsciiDoc to HTML, PDF, and ePub rendering examples]
. ziontee113, https://www.youtube.com/watch?v=8fCkt5qgHw8[Conceal Boilerplate Code with Treesitter - Neovim Tips].
