= 자료구조
An Nyeong <me@annyeong.me>
:keywords: data-structure

> 나쁜 프로그래머는 코드를 신경씁니다. 훌륭한 프로그래머는 자료구조와 자료구조 사이의 관계를 신경씁니다.
> -- 리누스 토르발즈, https://lwn.net/Articles/193245/[Re: Licensing and the library version of git]

> 올바른 자료구조로 구성했다면 알고리즘은 언제나 자명합니다. 알고리즘이 아니라 자료구조가 프로그래밍의 핵심입니다.
> -- 롭 파이크, http://doc.cat-v.org/bell_labs/pikestyle[Notes on Programming in C]

== 추상 자료형

. 스택과 큐
. 우선순위 큐
. 딕셔너리

== 그래프

. 트리
.. 이진트리
... AVL, 레드블랙 트리
.. <<trie.adoc#>>

=== 우선순위 큐

특정 우선순위에 따라 값을 추출하는 자료구조. 스택과 큐와 다르게 삽입된 순서와 무관하게 우선순위에 따라서만
값을 추출한다. 값이 큰 것부터 추출하거나, 작은 것부터 추출할 수 있다.
리스트에 담고 계속 정렬하는 것보다 효율적이다.

==== 연산

stem:[\text{insert}(Q, x)]:::
우선순위 큐 stem:[Q]에 값 stem:[x]를 삽입한다.

stem:[\text{peek}(Q)]:::
우선순위 큐 stem:[Q]에서 가장 큰/작은 값을 찾아 반환한다.

stem:[\text{pop}(Q)]:::
우선순위 큐 stem:[Q]에서 가장 큰/작은 값을 추출하여 반환한다.

==== 구현

선형 리스트에 단순하게 저장하면 비효율적이다. 정렬을 해도, 하지 않아도 마찬가지이다.

정렬 안 된 선형 리스트에 보관해보자. 삽입할 때에 새 값과 이미 알고 있는 가장 큰/작은 값을 비교하여 이를
유지하자. 삽입할 때에는 비교하고 리스트 뒤에 추가하면 되므로 insert는 stem:[O(1)]이다. 가장 큰/작은
값을 찾을 때에는 보관한 값을 그냥 반환하면 되므로 peek도 stem:[O(1)]이다.
pop이 문제다. 정렬 되지 않았으므로 값을 열심히 찾아서 지워야하므로 stem:[O(n)]이다.

정렬 해도 크게 다르지 않다. 이미 정렬되어있으므로 pop과 peek는 stem:[O(1)]이지만, 삽입할 때
삽입정렬을 해야하므로 stem:[O(n)]이다.

이진 탐색을 사용해서 시간을 줄인다 해도 리스트 형태를 유지해야하므로 여전히 효율적이지 않다.
일반적으로는 이진 트리를 이용해서, 특히 이진 힙을 이용해 구현한다. Rust 표준 라이브러리에서도
https://doc.rust-lang.org/std/collections/struct.BinaryHeap.html[BinaryHeap]이라는
이름으로 구현되어 있다.

|===
|연산 |정렬 안 된 선형 리스트 |정렬된 선형 리스트 |이진 트리

|insert
|stem:[O(1)]
|stem:[O(n)]
|stem:[O(\log{n})]

|peek
|stem:[O(1)]
|stem:[O(1)]
|stem:[O(1)]

|pop
|stem:[O(n)]
|stem:[O(1)]
|stem:[O(\log{n})]

|===

== 연속과 연결

자료구조는 어떻게 메모리에 저장하느냐에 따라 크게 연속적인 것과 연결적인 것으로 나눌 수 있다.
배열과 같은 연속적인 자료구조는 메모리에 연속적인 공간을 할당하여 정보를 저장한다.
연결 리스트와 같은 연결적인 자료구조는 정보를 잘게 쪼개고 포인터를 이용하여 논리적으로
연결한다.

[bibliography]
== 참고
- Steven S. Skiena, "The Algorithm Design Manual".
- 와타노베 유타카, "프로그래밍 대회 공략을 위한 알고리즘과 자료 구조 입문".
- 박정흠, "자료구조". 가톨릭대학교.
- Buck Shlegeris, https://edykim.com/ko/post/advice-on-learning-algorithms/[알고리즘 학습에 대한 조언]. 김용균 번역.
- https://www.youtube.com/watch?v=algDLvbl1YY
