= dgrep 구현하기
An Nyeong <me@annyeong.me>
:description: dgrep을 구현하며 동시성을 공부하자

동시성에 대해 공부해야겠다는 생각을 하던 중 https://tech.devsisters.com/posts/server-position-coding-test/[데브시스터즈 서버 직군은 왜 코딩 면접을 볼까?]라는 글을 접하였다.

해당 글에서 정의한 dgrep 요구사항을 여러가지 모델로 구현해보며 동시성을
공부해보자.

== 문제 정의 및 분석

원문 문제는 아래와 같다:

```
용감한 쿠키는 평소 사용하는 파일 내 문자열 검색 툴 grep보다 더 빠른 속도를
자랑하는 ack나 ag같은 다양한 툴들이 있다는 것을 들었다.
자신만의 dgrep을 만들어 널리 세상을 이롭게 하고 싶다고 생각하게 된 용감한 쿠키는
그 첫 단계로 멀티스레드로 동작하는 grep을 직접 만들어보기로 결심하였다.
원하는 스펙에 맞는 파일 내 문자열 검색 툴을 만들어보자.

입력 형식
 - dgrep {keyword} {relative path}

출력 형식
 - 파일의 각 line에 keyword가 있는 경우, 해당 파일과 줄 번호를 출력한다.

조건
1. relative path가 디렉토리인 경우 디렉토리 내 모든 파일에 대해 검사를 진행한다.
2. relative path 내에 또 다른 디렉토리가 존재하는 경우, 각 디렉토리 내 모든 파일에 
대한 검사 또한 진행한다.
3. 멀티 스레드를 이용하여 최대한 빠르게 작업을 완료하도록 작성한다.
4. 동일한 파일에 대한 검사 결과는 한 번에 출력되어야 한다.
5. Directory 내 symlink는 없다고 가정한다.
6. 파일들은 모두 UTF8 인코딩으로 작성된 Text파일이라고 가정한다.
```<<dg>>

별다른 명시가 없는 부분은 내멋대로 해석하였다:

* Regex 검색은 구현하지 않는다.
* 여러 줄 검색은 구현하지 않는다.

== 왜 동시성인가

왜 동시성이 이 문제에 대한 적합한 해결책인지 점검하고 넘어가자.
주어진 디렉토리 내의 파일에서 문자열 패턴을 찾는 'grep'의 동작을 간단하게
생각하면 아래와 같을 것이다:

1. 파일 목록을 얻는다.
2. 파일 내용을 읽는다.
3. 문자열에서 패턴을 찾는다.
4. 출력한다.

이를 싱글 스레드에서 실행한다고 생각해보자. 1번과 2번, 4번은 운영체제가 할
일이다. 어플리케이션은 운영체제에 시스템 콜로 작업을 의뢰하고 가만히 있을
것이다. 3번은 어플리케이션이 하는 일이다. 메모리에서 패턴을 검색할 동안
운영체제는 가만히 있을 것이다.

좋은 성능을 내기 위해서는 운영체제와 어플리케이션 모두 바쁘게 일해야한다.
문자열에서 패턴을 찾으면서 동시에 다음에 읽을 파일을 목록에서 찾아 메모리에
로드할 수 있다면 가장 최적의 성능을 발휘할 것이다. 이를 위해서는 동시성 모델이
필요하다.

== 성능 측정

각 모델 별로 성능이 좋은지 나쁜지를 알아보기 위해서는 적절한 성능 측정 방법이
필요하다. 주어지는 상황에 따라 같은 모델이라도 성능이 다를 터이다. 어떻게 하면
최대한 객관적으로 성능을 측정할 수 있을까? 어떤 요소들이 성능에 영향을 끼칠까?
간단하게 생각해보았을 때 네 가지 요소가 떠올랐다:

파일의 개수:::
  파일의 개수가 많을수록 디스크IO가 더 많이 필요하다.
파일의 크기:::
  어떤 파일은 메모리에 올리기에는 크기가 너무 클 수도 있다.
검색 결과의 수:::
  생각 없이 출력한다면 각 파일 별 검색 결과가 뒤섞일 수 있다.
  한 파일의 검색 결과만 온전히, 줄 번호와 함께 출력하려면 이를 잘 직렬화해야하고
  이 또한 성능에 영향을 미칠 수 있다.

오늘날 grep 대신 많이 쓰는 ripgrep은 사용 패턴에 근거하여 두 가지 갈래로
벤치마킹 하였다.<<rg>>

큰 디렉토리에서 검색하기:::
+
파일의 개수가 많은 상황이다.
프로젝트에서 특정 코드를 검색하는 사용 패턴이 이에 해당한다.
ripgrep에서는 리눅스의 특정 커밋을 가져와 빌드 후 검색하였다. 
 
큰 단일 파일에서 검색하기:::
+
파일의 크기가 큰 상황이다.
로그 파일에서 검색하는 사용패턴이 이에 해당한다.
ripgrep에서는 https://opus.nlpl.eu/OpenSubtitles2016.php[OpenSubtitles2016 데이터셋]에서
자료를 가져와 검색하였다.

== 싱글 스레드 모델

성능을 신경쓰지 않고 간단하게 구현해보자.

. relative path를 확인한다.
. 읽은 경로가 텍스트 파일이면:
.. 텍스트 파일을 읽어서 줄마다 keyword가 있는지 검사한다.
.. keyword가 있다면 파일 이름, 줄 번호와 함께 해당 줄을 출력한다.
. 읽은 경로가 디렉토리면:
.. 해당 디렉토리 내의 모든 파일에 대해 동일하게 똑같이 읽는다.

문제를 그대로 서술한 것에 불과하므로 

.dgrep.rb
[source, ruby]
----
def grep(keyword, relative_path)
  if File.directory? relative_path
    Dir.open(relative_path).each_child do |child|
      path = File.join(relative_path, child)
      grep keyword, path
    end
  elsif File.readable? relative_path
    find_keyword_from_file keyword, relative_path
  end
end
----

.동시성 모델
* 싱글 스레드 모델
* 멀티 스레드 모델
* 액터 모델
* CSP 모델

[bibliography]
== 참고

- [[[dg]]] 황재영, https://tech.devsisters.com/posts/server-position-coding-test/[데브시스터즈 서버 직군은 왜 코딩 면접을 볼까?], 2022.
- 지민규, https://tech.devsisters.com/posts/programming-languages-5-concurrent-programming/[9가지 프로그래밍 언어로 배우는 개념: 5편 - 동시성 프로그래밍], 2023.
- [[[rg]]] Andrew Gallant, https://blog.burntsushi.net/ripgrep/[ripgrep is faster than {grep, ag, git grep, ucg, pt, sift}], 2016.
