= OpenWrt에 WireGuard 설치하기
An Nyeong <me@annyeong.me>
:description:
:keywords:
:created_at: 2023-12-31 10:54:39

외부에서도 편리하게 로컬 네트워크에 있는 것처럼 써보자.

== VPN

암호화 터널이라고 생각하는 것이 편리하다. 장치 A, B 사이에 암호화 터널을 구축한다. 장치 A에서 외부로 보내는 요청은 터널을 통과하여, 외부에서는 마치 장치 B의 요청처럼 보이게 된다.

따라서:

. A 네트워크에 있는데 마치 B 네트워크에 있는 것처럼 행동할 수 있다.
.. 따라서 국가나 위치를 숨길 수 있다.
. 신뢰할 수 없는 네트워크에서, 요청을 암호화해버린 후 신뢰할 수 있는 네트워크로 보내어 처리할 수 있다.
. 실제 IP 주소를 숨길 수 있다.

자꾸 숨길 수 있다고 해서 수상한 기술처럼 보이는데, 이럴 때 유용하게 쓸 수 있다:

. 원격지에서 로컬 네트워크로 접근할 수 있다 -- 개발용, 개인용 등 목적으로 로컬 네트워크에 띄운 프로그램은 외부에서 접속이 어렵다. VPN을 이용하여 해당 네트워크로 접속하면 마치 로컬 네트워크에 접속한 것처럼 이용할 수 있다.
. 원격지에서 특정 네트워크에 있는 것처럼 할 수 있다 -- 예를 들어 개발 목적으로 만든 데이터베이스를 집에서만 접속할 수 있도록 보안 설정을 해두었는데 외부에서 접속해야 할 수도 있다. 이때 외부 인터넷에 대해 새롭게 포트를 열어주는 것보다 필요할 때 집 네트워크에 VPN으로 접속하는 것이 안전하고 편리하다.
. 공공 와이파이의 경우 보안이 취약하다. 다른 누군가가 내 요청을 들여볼 수도 있다. VPN을 이용하면 암호화 터널로 동작하므로 안전하게 이용할 수 있다.

== WireGuard

OpenVPN, IPsec, WireGuard 등 다양한 프로토콜이 있다. 그중 WireGuard는 리눅스 커널 5.6부터 커널에 내장되어 편리하게 이용할 수 있다.

. 이미 커널에 내장되어 있어 별도 설치가 필요 없다.
. 다른 프로토콜에 비해 설정이 매우 간편하다.
. 속도가 빠르다.
. 로밍 기술이 적용되어 있어 중간에 네트워크가 끊겨도, 다시 연결하면 끊임 없이 이용할 수 있다.

macOS, iOS 앱이 있어 해당 앱을 설치하면 모바일 기기에서도 쓸 수 있다.

== OpenWrt

<<openwrt#,OpenWRT>>

집 라우터는 OpenWrt가 깔려있다. 여기에 WireGuard를 설정하여 VPN 서버로 활용하자.
웹 UI인 LuCI에서도 설정할 수 있고, SSH로 접속하여 셸 환경에서도 설정할 수 있다. 여기서는 셸 명령어를 기술한다.

== 설치

WireGuard는 커널에 포함되어 있으나 관리도구는 별도 설치가 필요하다. 아래 패키지를 설치하면 LuCI에서 WireGuard를 설정할 수 있다. `qrencode` 패키지는 나중에 피어 설정을 QR코드로 내보내기 위하여 필요하다.

[source, bash]
----
opkg update
opkg install luci-proto-wireguard luci-app-wireguard qrencode
/etc/init.d/network restart
----

`network restart` 하면 셸 접속이 끊어지므로 재접속이 필요하다.

혹은:
. LuCI → System → Software에 접속하여 두 패키지를 찾아 설치한다.
. LuCI → System → Startup → Initscripts → network에서 restart를 누른다.

== 인터페이스 생성하기

새로운 프로토콜(WireGuard)을 사용하기 때문에 통신을 위해서 새로운 인터페이스를 정의해야한다.
LuCI에서도 할 수 있고, 셸로도 할 수 있는데, LuCI에서 하는 것이 편리하다. 키 생성까지 한 번에 할 수 있다.
WireGuard는 공개키를 이용해 암호화한다.

. LuCI → Network → Interfaces에 접속한다
. ``Add new interface...``를 눌러 새 인터페이스를 만든다.
.. 이름은 편한대로 짓는다. ``wg0``이 관례인듯.
.. 프로토콜은 ``WireGuard VPN``을 고른다.
. General Settings
.. ``Generate new key pair``를 눌러 키쌍을 생성한다.
.. Listen Port: 그냥 두면 랜덤으로 하나 잡는다.
.. IP Addresses: 인터페이스에 할당할 대역. ``10.9.0.1/24``로 추가하였다.
. Peers -- 각 접속자 대한 설정을 할 수 있다.
.. ``Generate new key pair``를 눌러 키쌍을 생성한다.
.. Allowed IPs: 피어에게 허용할 IP 대역. ``10.9.0.0./24``로 추가하였다.
.. 설정 후 ``Generate configuration...``을 눌러 설정을 내보낸다.
.. 사용할 피어(휴대폰, 노트북 등 접속할 장치)의 WireGuard 앱에 해당 설정을 등록한다.

여기서 키쌍을 두 번 생성한다.

* 호스트의 키쌍.
** 비밀키: 호스트가 갖고 있는다.
** 공개키: 피어에게 공유한다.
* 피어의 키쌍. 피어에서 생성해도 된다.
** 비밀키: 피어가 갖고 있는다.
** 공개키: 호스트에게 공유한다.

== 방화벽 개방하기

이제 방화벽을 개방해주어야한다. LuCI → Network → Firewall에서 설정 할 수 있다. 이 작업은 ``/etc/config/firewall``을 수정하여서 할 수도 있다.

. LuCI → Network → Firewall
. General Settings 하단의 Zones에서 Add를 눌러 존을 만든다.
.. Name: 원하는 이름으로 한다. 여기서는 wireguard로 하였다.
.. Input/Output: Accept
.. Forward: Reject
.. Masquerading: 체크하라는데 뭔지는 모르겠다.
.. MSS clamping: 체크하라는데 뭔지는 모르겠다.
.. Covered Networks: 아까 만든 wg0
.. Allow forward to destination zones: 이 존에서 어떤 존으로 갈 수 있는 지를 묻는 것이다. VPN으로 접속시 내부 네트워크와 외부망을 모두 쓰고 싶으므로 lan, wan을 고른다
.. Allow forward to source zones: 외부망에서는 접근을 원치 않으므로 lan만 고른다.
. Traffic Rules 탭에 들어가 Add를 누른다.
.. Name: 작명 규칙에 맞게 Allow-Wireguard로 하자.
.. Protocol: wireguard는 UDP를 사용하므로 UDP만 체크한다
.. Source zone: 외부에서의 접속이므로 wan에 체크한다.
.. Destination port: 기본 wireguard 포트인 51820을 쓴다.
.. Action: 당연히 accept

[bibliography]
== 참고

. https://www.wireguard.com/[WireGuard]
