name: Deploy to hanassig-pub

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Dispatch call to hanassig-web
        run: |
          curl -L \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/nyeong/nyeong.github.io/actions/workflows/deploy.yaml/dispatches" \
            -d '{"ref": "main"}'
