name: Deploy to hanassig-web

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Dispatch call to hanassig-web
        run: |
          curl \
            -XPOST \
            -u "${{ secrets.WORKFLOW_AUTH }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/nyeong/hanassig-web/actions/workflows/build.yml/dispatches" \
            -d '{"ref": "main", "inputs": {"job": "build"}}'
