on:
	issues:
		types:
			- labeled
			- edited

jobs:
	issue_to_markdown:
		steps:
			- uses: actions/checkout@v3
				with:
					token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

			- uses: eunjae-lee/issue-to-markdown@v0
				with:
					token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

			- uses: stefanzweifel/git-auto-commit-action@v4
				with:
					commit_message: 'update contents via github action'
